w8d1/reddit_clone/config/routes.rb
# == Route Map
#
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#                     users POST   /users(.:format)                                                                         users#create
#                  new_user GET    /users/new(.:format)                                                                     users#new
#                      user DELETE /users/:id(.:format)                                                                     users#destroy
#               new_session GET    /session/new(.:format)                                                                   sessions#new
#                   session DELETE /session(.:format)                                                                       sessions#destroy
#                           POST   /session(.:format)                                                                       sessions#create
#                      subs GET    /subs(.:format)                                                                          subs#index
#                           POST   /subs(.:format)                                                                          subs#create
#                   new_sub GET    /subs/new(.:format)                                                                      subs#new
#                  edit_sub GET    /subs/:id/edit(.:format)                                                                 subs#edit
#                       sub GET    /subs/:id(.:format)                                                                      subs#show
#                           PATCH  /subs/:id(.:format)                                                                      subs#update
#                           PUT    /subs/:id(.:format)                                                                      subs#update
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create, :destroy]

  resource :session, only: [:new, :create, :destroy]

  resources :subs, only: [:new, :create, :edit, :update, :show, :index]
  
end

w8d1/reddit_clone/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint           not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  sub_id     :integer          not null
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Post < ApplicationRecord

    validates :title, :author_id, :sub_id, presence: true
    validates :title, uniqueness: { scope: :sub_id }
  
    has_many :post_subs,
        foreign_key: :post_id,
        class_name: :PostSub,
        dependent: :destroy

    has_many :subs,
        through: :post_subs,
        source: :sub

    belongs_to :author,
        foreign_key: :author_id,
        class_name: :User

end

w8d1/reddit_clone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
 
  def show
    render :show
  end

  def new
    @post = Post.new
    render :new
  end

  def edit
    if is_current_user?(@post.author_id)
      render :edit
    else
      flash[:errors] = ["You are not the author of this post!"]
      redirect_to post_url(@post)
    end
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id
    @post.sub_ids = post_params[:sub_ids]
    debugger
    if @post.save
      params[:post][:sub_ids].each do |sub_id|
      PostSub.create!(sub_id: sub_id, post_id: @post.id)
    end 
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def update
    if @post.update_attributes(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def destroy
    if is_current_user?(@post.author_id)
      @post.destroy
      redirect_to sub_url(@post.sub_id)
    else
      flash[:errors] = ["You are not the author of this post!"]
      redirect_to post_url(@post)
    end
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :url, :content, sub_ids: [])
    end
end

w8d1/reddit_clone/app/helpers/posts_helper.rb
module PostsHelper
end

w8d1/reddit_clone/app/views/posts/_form.html.erb
<% if is_edit %>
    <% action = post_url(post.id) %>
    <% button_text = "Save Changes" %>
<% else %>
    <% action = posts_url %>
    <% button_text = "Create Post" %>
<% end %>

<form action="<%= action %>" method="post">
    <% if is_edit %>
        <input type="hidden" name="_method" value="patch">
    <% end %>
        <%= auth_token %>

            <label for="title">Title</label>
            <br>
            <input type="text" name="post[title]" id="title" value="<%= post.title %>">

            <br>

            <label for="content">Content</label>
            <br>
            <textarea name="post[content]" id="content" cols="30" rows="10"><%= post.content %></textarea>
            <br>
            <p>Post to Subs:</p>
            <br>
            <input type="hidden" name="post[sub_ids][]" value="">
            <% Sub.all.each do |sub| %>
                <label>
                  <input type="checkbox" name="post[sub_ids][]" value="<%=sub.id%>" <%= "checked" if post.sub_ids.include?(sub.id) %> >
                  <%= sub.title %>
                </label>
            <% end %>
            
            <br>
            <br>
            <button><%= button_text %></button>
            
</form>

w8d1/reddit_clone/app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post, is_edit: true %>

w8d1/reddit_clone/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post, is_edit: false %>

w8d1/reddit_clone/app/views/posts/show.html.erb
<h1><%= @post.title %> by <%= @post.author.username %></h1>
<h2>Content</h2>
<p>
    <%= @post.content %>
</p>