w7d2/music_app/config/routes.rb
Rails.application.routes.draw do
  resources :bands do 
    resources :albums, only: :index
  end

  resources :albums
  resources :users, only: [:create,:new]
  resource :session, only: [:new,:create,:destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: redirect('/bands')
end

w7d2/music_app/app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :bigint           not null, primary key
#  title      :string           not null
#  year       :integer          not null
#  studio?    :boolean          not null
#  band_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Album < ApplicationRecord
    validates :title, :year, :studio?, :band_id, presence:true

    belongs_to :band
end

w7d2/music_app/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Band < ApplicationRecord
    validates :name, presence:true

    has_many :albums
end

w7d2/music_app/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord
    validates :email, :session_token, presence:true
    validates :email, :session_token, uniqueness:true
    validates :password_digest, presence: { message: "can't be blank" }
    validates :password, length: { minimum:6, allow_nil: true}

    before_validation :ensure_session_token

    attr_reader :password
    
    def self.find_by_credentials(email,password)
        user = User.find_by(email: email)
        return user if user && user.is_password?(password)
        nil
    end
    
    def self.generate_session_token
        SecureRandom::urlsafe_base64
    end

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def ensure_session_token
        self.session_token ||= User.generate_session_token
    end


    def reset_session_token!
        session_token = User.generate_session_token
        self.save!
        self.session_token
    end

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end
end

w7d2/music_app/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
    before_action :get_band, only: :index
    before_action :set_album, only: [:edit, :update]

    def index
        @albums = @band.albums
        render :index
    end

    def show
        @album = Album.find(params[:id])
        render :show
    end

    def new
        @album = Album.new
        render :new
    end

    def create
        @album = Album.new(album_params)

        if @album.save
            redirect_to albums_url
        else
            render :new
        end
    end

    def edit
        render :edit
    end

    def update 
        if @album.update(album_params)
            redirect_to album_url(@album)
        else
            render json: @album.errors.full_messages, status: 422
        end
    end
    
    def destroy
        @album.destroy

        redirect_to albums_url
    end

    private
    def album_params
        params.require(:album).permit(:title, :year, :studio?, :band_id)
    end

    def set_album
        @album = Album.find(params[:id])
    end

    def get_band
        @band = Band.find(params[:band_id])
    end

end

w7d2/music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?
    
    def login!(user)
        session[:session_token] = user.reset_session_token!
        @current_user = user
    end

    def logout!
        @current_user.reset_session_token!
        @current_user = nil
        session[:session_token] = nil
    end

    def current_user
        @current_user ||= User.find_by( session_token: session[:session_token] )
    end

    def logged_in?
        !!@current_user
    end

    def ensure_logged_in
        redirect_to new_session_url unless logged_in?
    end
end

w7d2/music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :set_band, only: [:show, :edit, :update, :destroy]

  def index
    @bands = Band.all
    render :index
  end

  def new
    @band = Band.new
    render :new
  end

  
  def create
    @band = Band.new(band_params)

    if @band.save
      redirect_to bands_url
    else
      render :new
    end
  end

  def edit
    render :edit
  end

  def destroy
    @band.delete
    redirect_to bands_url
  end


  private
    def set_band
      @band = Band.find(params[:id])
    end

    def band_params
      params.require(:band).permit(:name)
    end
end

w7d2/music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
    def new
        
        @user = User.new
        render :new
    end

    def create
        user = User.find_by_credentials(
            params[:user][:email],
            params[:user][:password]
        )
        
        if user
            login!(user)
            redirect_to bands_url
        else
            flash.now[:errors] = ["Invalid credentials!"]
            # redirect_to new_session_url
            render :new
        end
    end

    def destroy
        logout!
        redirect_to new_session_url
    end
end

w7d2/music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login!(@user)
      redirect_to bands_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private
    def user_params
      params.require(:user).permit(:email, :password, :session_token)
    end
end

w7d2/music_app/app/helpers/bands_helper.rb
module BandsHelper
end

w7d2/music_app/app/views/albums/_form.html.erb
<% if is_edit %>
    <% action = album_url(album) %>
    <% button_text = "Edit this album" %>
<% else %>
    <% action = new_album_url %>
    <% button_text = "Add a new album" %>
<% end %>


<form action="<%= action %>" method="post">
  <%= auth_token %>

    <% if is_edit %>
        <input type="hidden" name="_method" value="patch">
    <% end %>

  <label for="title">Album Title: </label>
  <input id="title" type="text" name="album[title]" value="<%= @album.title %>">
  <br>
  <br>

  <label for="year">Album Year: </label>
  <input id="year" type="text" name="album[year]" value="<%= @album.year %>">
  <br>    
  <br>

  <label for="band">Album Artist: </label>
    <br>
    <% Band.all.each do |artist| %>
    <label>
        <input type="radio" 
        name="album[band_id]" 
        value="<%= artist.id %>"
        <%= "checked" if album.band.name == artist %>>
        <%= artist.name %>
    </label>
    <br>
    <% end %>
    <br>    
    <br>

  <input type="submit" value="<%= button_text %>">
</form>

w7d2/music_app/app/views/albums/edit.html.erb
<h1>Editing Albums</h1>

<%= render "form", is_edit: true, album: @album %>

<%= link_to 'Back', albums_path %>

w7d2/music_app/app/views/albums/index.html.erb
<h1> <%= @band.name %> Albums</h1>

<table id="albums">
  <thead>
    <tr>
      <th>Album Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @albums.each do |album| %>
      <tr>
        <td><%= album.title %></td>
        <td><a href="<%= album_url(album) %>"> Show Album </a></td>
        <td><a href="<%= album_url(album) %>"> Edit Album </a></td>
        <td><form action="<%= album_url(album) %>" method = "POST">
          <input type="hidden" name="_method" value="DELETE"> 
          <%= auth_token %>
          <input type="submit" value="Delete Album!"> </form></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Album', new_album_path %>

w7d2/music_app/app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render 'form', is_edit: false, album: @album %>

<%= link_to 'Back', albums_path %>

w7d2/music_app/app/views/albums/show.html.erb
<h1>Album by <%= @album.band.name %></h1>

<p><%= @album.title %></p>
<p>Artist: <%= @album.band.name %></p>
<a href="<%= edit_album_url(@album) %>">Edit this album</a>
<form action="<%= album_url(@album) %>" method="post">
    <input type="hidden" name="_method" value="delete">
    <button>Delete this album</button>
</form>
<a href="<%= band_albums_url(@album.band) %>"><- Back to Index</a>

w7d2/music_app/app/views/bands/_form.html.erb
<% if is_edit %>
    <% action = edit_band_url(band) %>
    <% button_text = "Edit this band" %>
<% else %>
    <% action = new_band_url %>
    <% button_text = "Add a new band" %>
<% end %>

<form action="<%= action %>" method="post">
  <%= auth_token %>

  <% if is_edit %>
      <input type="hidden" name="_method" value="patch">
  <% end %>

  <label for="name">Band Name: </label>
  <input id="name" type="text" name="band[name]" value="<%= @band.name %>">

  <input type="submit" value="<%= button_text %>">
</form>

w7d2/music_app/app/views/bands/edit.html.erb
<h1>Editing Band</h1>

<%= render "form", is_edit: true, band: @band %>

w7d2/music_app/app/views/bands/index.html.erb
<p id="notice"><%= notice %></p>


<table id="bands" class="band-table">
  <thead>
    <tr>
      <th>Band Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bands.each do |band| %>
      <tr>
        <td class="band-name"><%= band.name %></td>
        <td><a class="band-link" href="<%= band_albums_url(band) %>"> Show Band </a></td>
        <td><a class="band-link" href="<%= edit_band_url(band) %>"> Edit Band </a></td>
        <td><form class="band-link" action="<%= band_url(band) %>" method = "POST">
          <input type="hidden" name="_method" value="DELETE"> 
          <%= auth_token %>
          <input type="submit" value="Delete Band!"> </form></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button id="band-button" class="user-buttons"><%= link_to 'New Band', new_band_path %></button>

w7d2/music_app/app/views/bands/new.html.erb
<h1>New Band</h1>

<%= render "form", is_edit: false, band: @band %>

<%= link_to 'Back', bands_path %>

w7d2/music_app/app/views/bands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @band.name %>
</p>

<%= link_to 'Edit', edit_band_path(@band) %> |
<%= link_to 'Back', bands_path %>

w7d2/music_app/app/views/users/_form.html.erb
<% if is_create %>
  <% action = users_url %>
  <% button_text = "Create User" %>
<% else %>
  <% action = session_url %>
  <% button_text = "Log In" %>
<% end %>


<form class="log-in-form" action="<%= action %>" method="post">
  <%= auth_token %>


  <label for="email">Email</label>
  <input id="email" type="text" name="user[email]" value="<%= user.email %>">

  <label for="password">Password</label>
  <input id="password" type="password" name="user[password]" value="<%= user.password %>">

  <input class="submit" type="submit" value="<%= button_text %>">
</form>

w7d2/music_app/app/views/users/new.html.erb
<%= render 'form', user: @user, is_create: true %>

<button id="back-button" class="user-buttons"><%= link_to 'Back', bands_path %></button>

w7d2/music_app/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password_digest %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>